<<<<<<< HEAD
theme: jekyll-theme-minimal
title: SerumHydra's Website
description: A place where my information on my twitch, youtube, and github projects will be posted
=======
theme: jekyll-theme-minimal
>>>>>>> 53f59c7825444cd929aebb7935326bd3afde30cd
